Ej02_Empresa/Ej02_Empresa/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.controlEmpleado.urls')),
    re_path('', include('applications.controlDepartamento.urls')),
]

Ej02_Empresa/applications/controlDepartamento/urls.py
from django.contrib import admin 
from django.urls import path
from . import views 

app_name = 'controlDepartamento_app'

urlpatterns = [
    path('newdepartamento/', views.NewDepartamentoView.as_view(), name='nuevodepartamento'),
    path('listaDepartamentos/', views.ListEmpleadoByDpto.as_view(), name='lista_Departamento'),
]

Ej02_Empresa/applications/controlEmpleado/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "controlEmpleado_app"

urlpatterns = [
    path(
        "listatodosempleados/", views.ListAllEmpleados.as_view(), name="empleados_all"
    ),
    path(
        "listapordepartamento/<valDpto>",
        views.ListByDptoEmpleado.as_view(),
        name="ver_pordpto",
    ),
    path(
        "listabusquedaempleado/",
        views.ListaEmpleadoByKword.as_view(),
        name="busqueda_empleado",
    ),
    path("listacursosxempleado", views.ListaDeCursosEmpleado.as_view()),
    path("verempleado/<int:pk>", views.DetalleEmpleado.as_view(), name="ver_empleado"),
    path("crearempleado/", views.CrearEmpleado.as_view(), name="crear_empleado"),
    path("successempleado/", views.SuccesView.as_view(), name="registro_correcto"),
    path("deleteempleado/", views.SuccesView2.as_view(), name="registro_eliminado"),
    path("signin/", views.Sesion.as_view(), name="signin"),
    path(
        "updateempleado/<int:pk>",
        views.UpdateEmpleado.as_view(),
        name="Actualizar_registro",
    ),
    path(
        "deleteempleado/<int:pk>",
        views.DeleteEmpleado.as_view(),
        name="Borrar_Registro",
    ),
    path("", views.InicioView.as_view(), name="inicio"),
]

Ej02_Empresa/templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <a
          href="{% url 'controlEmpleado_app:inicio' %}"><strong>Inicio</strong></a>
      </li>
      <li>
        <a href="{% url 'controlEmpleado_app:empleados_all' %}">Empleados</a>
      </li>
      <li><a
          href="{% url 'controlDepartamento_app:lista_Departamento' %}">Departamentos</a></li>
      <li><a href="#" class="disabled">Administrar</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><a href="{% url 'controlEmpleado_app:crear_empleado' %}"
          class="button">Empleado Nuevo</a></li>
      <!-- <li style="margin-left: 4px;"><a
          href="{% url 'controlEmpleado_app:signin' %}"
          class="button success">Sign In</a></li> -->
    </ul>
  </div>
</div>