Ej02_Empresa/Ej02_Empresa/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.controlEmpleado.urls')),
    re_path('', include('applications.controlDepartamento.urls')),
]

Ej02_Empresa/applications/controlEmpleado/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "controlEmpleado_app"

urlpatterns = [
    path(
        "listatodosempleados/", views.ListAllEmpleados.as_view(), name="empleados_all"
    ),
    path(
        "listapordepartamento/<valDpto>",
        views.ListByDptoEmpleado.as_view(),
        name="ver_pordpto",
    ),
    path(
        "listabusquedaempleado/",
        views.ListaEmpleadoByKword.as_view(),
        name="busqueda_empleado",
    ),
    path("listacursosxempleado", views.ListaDeCursosEmpleado.as_view()),
    path("verempleado/<int:pk>", views.DetalleEmpleado.as_view(), name="ver_empleado"),
    path("crearempleado/", views.CrearEmpleado.as_view(), name="crear_empleado"),
    path("successempleado/", views.SuccesView.as_view(), name="registro_correcto"),
    path("deleteempleado/", views.SuccesView2.as_view(), name="registro_eliminado"),
    path("signin/", views.Sesion.as_view(), name="signin"),
    path(
        "updateempleado/<int:pk>",
        views.UpdateEmpleado.as_view(),
        name="Actualizar_registro",
    ),
    path(
        "deleteempleado/<int:pk>",
        views.DeleteEmpleado.as_view(),
        name="Borrar_Registro",
    ),
    path("", views.InicioView.as_view(), name="inicio"),
]

Ej02_Empresa/templates/departamento/ListDepartamento.html
{% extends 'home/base.html' %}
    
{% block content %}
    <div class="grid-x">
        <h1 class="cell align-content-center " >Lista de Departamentos</h1>
        <div class="cell">
            <table class="stack">
                <thead>
                    <tr>
                        <th width="200"><b>ID</b></th>
                        <th width="250"><b>DEPARTAMENTO</b></th>
                        <th width="200"><b>ACCION</b></th>
                    </tr>
                </thead>
                <tbody>
                    {% for Departamento in Departamentos %}
                    <tr>
                        <td>{{ Departamento.id }}</td>
                        <td>{{ Departamento.nom }}</td>
                        <td><a class="button warning"
                                href="{% url 'controlEmpleado_app:ver_pordpto' Departamento.nom %}">ver Empleados</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

Ej02_Empresa/templates/departamento/new_departamento.html
<h1>Registrar Nuevo Departamento</h1>
<form method="POST">{% csrf_token %}
    <h3>Datos Departamento</h3>
    <p>{{form.nomDepa}}</p>
    <p>{{form.areaDepa}}</p>

    <h3>Datos Empleado</h3>
    <p> {{form.nomEmp}} </p>

    <button type="submit">Guardar</button>
</form>