Ej02_Empresa/Ej02_Empresa/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.controlEmpleado.urls')),
    re_path('', include('applications.controlDepartamento.urls')),
]

Ej02_Empresa/applications/controlEmpleado/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "controlEmpleado_app"

urlpatterns = [
    path(
        "listatodosempleados/", views.ListAllEmpleados.as_view(), name="empleados_all"
    ),
    path(
        "listapordepartamento/<valDpto>",
        views.ListByDptoEmpleado.as_view(),
        name="ver_pordpto",
    ),
    path(
        "listabusquedaempleado/",
        views.ListaEmpleadoByKword.as_view(),
        name="busqueda_empleado",
    ),
    path("listacursosxempleado", views.ListaDeCursosEmpleado.as_view()),
    path("verempleado/<int:pk>", views.DetalleEmpleado.as_view(), name="ver_empleado"),
    path("crearempleado/", views.CrearEmpleado.as_view(), name="crear_empleado"),
    path("successempleado/", views.SuccesView.as_view(), name="registro_correcto"),
    path("deleteempleado/", views.SuccesView2.as_view(), name="registro_eliminado"),
    path("signin/", views.Sesion.as_view(), name="signin"),
    path(
        "updateempleado/<int:pk>",
        views.UpdateEmpleado.as_view(),
        name="Actualizar_registro",
    ),
    path(
        "deleteempleado/<int:pk>",
        views.DeleteEmpleado.as_view(),
        name="Borrar_Registro",
    ),
    path("", views.InicioView.as_view(), name="inicio"),
]

Ej02_Empresa/templates/empleado/add_empleado.html
{% extends 'home/base.html' %}

{% block title %} Nuevo Registro {% endblock title %}

{% block content %}
<h1>Crear empleado</h1>
<form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button class="button" type="submit">Agregar</button>
</form>

{% endblock content %}

Ej02_Empresa/templates/empleado/delete_empleado.html
{% extends 'home/base.html' %}

{% block title %} Eliminar Registro {% endblock title %}

{% block content %}
<h1>Eliminar Empleado</h1>
<form method="post">{% csrf_token %}
    <p>*****DESEA ELIMINAR ESTE EMPLEADO*****</p>
    <button class="alert button" type="submit">Confirmar</button>
</form>
{% endblock content %}

Ej02_Empresa/templates/empleado/detail_empleado.html
<h1>Detalle de un empleado</h1>
{{ empleado }}

<h2>Todos los datos</h2>
<p>Id: {{ empleado.id }}</p>
<p>Nombre: {{ empleado.nom }}</p>
<p>Tipo: {{ empleado.tipo }}</p>
 <p>Departamento: {{ empleado.dpto }}</p>

Ej02_Empresa/templates/empleado/find_empleado.html
<h1>Buscar empleado por palabra clave</h1>
<form method="GET">{% csrf_token %}
    <label>Nombre</label>
    <input type="text" id="valNom" name="valNom" placeholder="Ingrese el nombre">
    <button type="submit">Buscar</button>
    
</form>

<h2>Lista Resultados</h2>
<ul>
    {%for rtaEmpleados in object_list%}
        <li>{{rtaEmpleados}}</li>
    {%endfor%}
</ul>

Ej02_Empresa/templates/empleado/list_all.html
{% extends 'home/base.html' %}

{% block content %}

<div class="grid-x">
    <h1 class="cell">Lista de Empleados</h1>
    <div class="cell grid-x grid-margin-x">
        <div class="cell large-7">
            <input type="text" placeholder="Buscar Empleado">
        </div>
        <div class="cell large-3">
            <a class="button success" href="">Buscar</a>
        </div>
    </div>
    <div class="cell">
        <table class="stack">
            <thead>
              <tr>
                <th width="200"><b>ID</b></th>
                <th width="250"><b>NOMBRE-APELLIDO</b></th>
                <th width="200"><b>ACCION</b></th>
              </tr>
            </thead>
            <tbody>
                {% for registro in object_list %}
              <tr>
                <td>{{ registro.id }}</td>
                <td>{{ registro.nom }}</td>
                <td>
				<a class="button warning" href="{% url 'controlEmpleado_app:Actualizar_registro' registro.id %}">Actualizar Registro</a>
				<a class="alert button" href="{% url 'controlEmpleado_app:Borrar_Registro' registro.id %}">Borrar Registro</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
</div>























<!-- <h1>Lista de Todos Los Empleados</h1>
<ul>
    {% for registro in object_list %}
        <li>{{registro}}</li>
    {% endfor %}
</ul>

{% if is_paginated %}
    <ul class="">

        {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
            </li>
        {% endif %}

        <li class="page-item">
            <a href="?page={{ page_obj.number }}" class="page-link">{{ page_obj.number }}</a>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a>
            </li>
        {% endif %}

    </ul>
{% endif %} -->

{% endblock content %}

Ej02_Empresa/templates/empleado/list_by_cursos.html
<h1>Buscar cursos de Empleados</h1>
<form method="GET">{% csrf_token %}
    <label><b>ID</b></label>
    <input type="number" id="valId" name="valId" placeholder="Ingrese el ID">
    <button type="submit">Buscar</button>
    
</form>

<h2>Cursos del Empleado</h2>
<ul>
    {%for rtaCursos in object_list%}
        <li>{{rtaCursos}}</li>
    {%endfor%}
</ul>

Ej02_Empresa/templates/empleado/list_by_dpto.html
{% extends 'home/base.html' %}
<h1>Lista de empleados por departamento</h1>

<!-- <ul>
    
    <li></li>
</ul> -->
<!-- {{ object_list }} -->
{% block content %}
<div class="grid-x">
<div class="cell">
    <table class="stack">
        <thead>
            <tr>
                <th width="200"><b>ID</b></th>
                <th width="250"><b>NOMBRE</b></th>
                <th width="200"><b>DEPARTAMENTO</b></th>
            </tr>
        </thead>
        <tbody>
            {% for registro in object_list %}
            <tr>
                <td>{{ registro.id }}</td>
                <td>{{ registro.nom }}</td>
                <td>{{registro.dpto}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% endblock content %}

Ej02_Empresa/templates/empleado/succes.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %} Resgistro Exitoso {% endblock title %}

{% block content %}

<h1 style="align-items: center;" class="estilo1"> Registro de Empleado
    Exitoso...</h1>

<!-- Buttons (actions) -->
<a style="margin-left: 12px;"
    href="{% url 'controlEmpleado_app:empleados_all' %}"
    class="submit success button">Ver Empleados</a>
{% endblock content %}

Ej02_Empresa/templates/empleado/succes2.html
{% extends 'home/base.html' %}

{% load static %}

{% block title %} Eliminar Empleado {% endblock title %}

{% block content %}

<h1 style="align-items: center;" class="estilo1"><em>Se ha Eliminado el Empleado
        de Forma Correcta...</em></h1>

<!-- Buttons (actions) -->
<a style="margin-left: 12px;"
    href="{% url 'controlEmpleado_app:empleados_all' %}"
    class="submit success button">Ver Empleados</a>
{% endblock content %}

Ej02_Empresa/templates/empleado/update_empleado.html
{% extends 'home/base.html' %}

{% block title %} Actualizacion de Datos {% endblock title %}

{% block content %}

<h1>Modificar datos de empleado</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button class="button warning" type="submit">Actualizar</button>
</form>

{% endblock content %}